name              "raptor"
maintainer        "ADADA, LLC"
maintainer_email  "chef@adadabase.com"
license           "MIT"
description       "Installs rasqal library from redland."
version           "0.1"
long_description  "Installs rasqal library from redland."
depends           "raptor"
